### ISSUE TITLE
Create a new Macro to generate Iso for case classes with a single accessor

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#119]
```scala
@Iso case class Price(value: Int)

Price.value.get(Price(2)) == 2
Price.value.reverse.get(2) == Price(2)
```
Or another name

Edit: use A dedicated macro for Iso

**Comment by julien-truffaut** [comment]
@dwijnand do you know how can we recognise that a case class has a single element?

**Comment by dwijnand** [comment]
Probably by either embedding in the quasiquote (https://github.com/julien-truffaut/Monocle/blob/9ca84b5d1d0874c4689a36555454bd232bcfd131/macro/src/main/scala/monocle/macros/Lenses.scala#L31-L42) there's only one constructor argument or simply adding a guard after the quasiquote

**Comment by julien-truffaut** [comment]
Thank @dwijnand 
done in #170
