### ISSUE TITLE
add optics for scalaz.Validation

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#153]

**Comment by mingp** [comment]
Hello @julien-truffaut. I saw your comment on Reddit /r/scala about getting started with contributing to Monocle with issues labeled "padawan friendly". Could you please clarify a few things about this issue and about Monocle in general?

* What is the recommended way to familiarize one's self with the Monocle code base? Are there any particular classes/methods/files to look at for examples?
* Approximately what components should be implemented for this issue? What documentation/tests should be updated to correspond to such?
* Any particular examples of existing code similar to what should be written for this issue which could be used as example/inspiration?

Thank you very much in advance!

**Comment by julien-truffaut** [comment]
Hi @mingp 

Sure, it might be a bit intimidating to dive into the code base. What's important is that you familiarize yourselves with a few Optics and how they relate to each other, for example I would have a look a `Lens`, `Prism` and `Optional` (module core, package monocle). Basically each of this optics is a pair of function (get / set, getMaybe / reverseGet and getMaybe / set respectively). The key point is that optics compose with each other to create new optics, e.g. if you compose a `Lens` with a `Optional` you get an `Optional` (cf diagram in readme).

Once you have done that you can have a look at `Maybe` and `Either` optics instances: https://github.com/julien-truffaut/Monocle/blob/master/core/src/main/scala/monocle/std/Maybe.scala and https://github.com/julien-truffaut/Monocle/blob/master/core/src/main/scala/monocle/std/Either.scala

This issue is about implementing similar optics but for `scalaz.Validation` (kind of an `Either` that accumulates failure). You can start with the one I described i.e. success, failure and validationToMaybe.

For testing, we generally use optics laws to verify our implementation. In other word, you have almost nothing to do, here are the tests for `Either`: https://github.com/julien-truffaut/Monocle/blob/master/test/src/test/scala/monocle/std/EitherSpec.scala

Don't hesitate if you have any questions, you can reach me or other people familiar with the library on irc or gitter (once I figure out how to access it fro my job ^^)

**Comment by anakos** [comment]
Hello-

Seeing as how the previous PR has been closed and remains unmerged, I'm going to take a stab at this if no one else is working on it.

Alex
