### ISSUE TITLE
add optics for scalaz.Cofree

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#177]
```scala
  def head[S[_], A]: Lens[Cofree[S, A], A]
  def tail[S[_], A]: Lens[Cofree[S, A], S[Cofree[S, A]]]

  def coffreeToNel[A]: Iso[Cofree[List, A], NonEmptyList[A]]
  def coffreeToTree[A]: Iso[Cofree[Stream, A], Tree[A]]
```

bonus points: make the optics polymorphic (i.e. `PLens` and `PIso` instead of `Lens` and `Iso`)

**Comment by LiamGoodacre** [comment]
Hello, I'm just about to play around with this as an entry point to the project.

When you say about using polymorphic optics, I can't see how `head` and `tail` can be generalized to `PLens` (other than trivially) given that they are only focusing on the top level of a `Cofree` structure and not every `head` and `tail` at all levels down.  (Although those could be nice `PTraversal`s to have.)

Also I don't believe `cofreeToNel` could be a valid `Iso` - The `Cofree List` has unrecoverable structure that will be forgotten.  If we pick a configuration of `Cofree List` to always convert to then we'd be vialating the `Iso` "modify identity" law: `iso modify id = id`.

A `PIso` for `cofreeToTree` will work though :smiley:

How does this sound?

~~~scala
def head[S[_], A]: Lens[Cofree[S, A], A]
def tail[S[_], A]: Lens[Cofree[S, A], S[Cofree[S, A]]]

def heads[S[_], A, B]: PTraversal[Cofree[S, A], Cofree[S, B], A, B]
def tails[S[_], A, B]: PTraversal[Cofree[S, A], Cofree[S, B], S[Cofree[S, A]], S[Cofree[S, B]]]

def cofreeToTree[A, B]: PIso[Cofree[Stream, A], Cofree[Stream, B], Tree[A], Tree[B]]
~~~

**Comment by julien-truffaut** [comment]
you're completely right, `head` and `tail` cannot be a `PLens`. In fact, rather than defining `head` and `tail` manually we can create an instance of `Cons1` for `Cofree` (see `monocle.std.nel` for an example).

You're also right about `coffreeToNel `, I believe it should be using `Option` and not `List`:
```scala
def coffreeToNel[A]: Iso[Cofree[Option, A], NonEmptyList[A]]
```

We recently adopted a pattern where we define polymorphic optics whenever we can using the prefix `p` and provide a monomorphic alias  e.g.
```scala
  def pCofreeToTree[A, B]: PIso[Cofree[Stream, A], Cofree[Stream, B], Tree[A], Tree[B]] = ...
  def cofreeToTree[A]: Iso[Cofree[Stream, A], Tree[A]] = pCofreeToTree[A, A]
```

It is bit boiler platty but polymorphic optics rarely play well with type inference, so it is convenient to define a monomorphic alias.

**Comment by LiamGoodacre** [comment]
Thanks, just had a look at `Cons1` - sounds like a good approach.

Should that preserve the laziness of the tail?

~~~scala
nonLazyTail : Cons1[Cofree[S, A], A, S[Cofree[S, A]]]
lazyTail : Cons1[Cofree[S, A], A, Free[Function0, S[Cofree[S, A]]]]
~~~

**Comment by LiamGoodacre** [comment]
Hmm, I'm not sure `Iso[Cofree[Option, A], NonEmptyList[A]]` is quite right.
The `Cofree[Option, A]` structure could potentially be infinite.
Would it make more sense to have `Iso[Cofree[Option, A], OneAnd[Stream, A]]`?

**Comment by julien-truffaut** [comment]
I think we can make `Cons1` preserves the laziness of `tail` for `head` `Lens` by overriding default implementation of `head` for `Cofree`.

Right, we should probably use `Stream` instead of `List` for `Cofree[Option, A]` since `tail` is a method and not a strict field.
