### ISSUE TITLE
@Lenses for case class with type parameters

### ISSUE THREAD

**Issue by refried** [julien-truffaut/Monocle#184]
`@Lenses case class Foo[A](a: A)`
 leads to
`[error] class Foo takes type parameters`
and sometimes (I haven't figured out the necessary conditions):
`[error] Invalid annotation target: must be a case class`
(it *is* a case class!)

**Comment by julien-truffaut** [comment]
Hi @refried 

At the moment, all macros does not support polymorphic optics, i.e. `@Lenses` can only generate `Lens` and not `PLens`. We have #114 to add this functionality.

 In the meantime, we should update the error message to something like "Invalid annotation target: must be a case class without type parameter".

**Comment by refried** [comment]
Thanks -- I might be mistaken, but I think that I want a `Lens` and not a `PLens`.  Eg:

```
object Foo {
  def a[A]: Lens[Foo[A], A] = ...
}
```

but I like your suggested error in the mean time.

**Comment by julien-truffaut** [comment]
it all depends if you want to modify the type of `Foo` with your lens e.g. `lens.modify(f: A => B)(fooA) == fooB`.

Btw, if your case class has a single accessor you can build an `Iso` instead of `Lens`, for example: 
```scala
def fooIso[A]: Iso[Foo[A], A] = Iso[Foo[A], A](_.a)(Foo.apply)
fooIso.get(Foo(a)) == a
fooIso.reverseGet(a) == Foo(a)
```

**Comment by refried** [comment]
Thanks — no, usually I have more fields, and don't need to modify the type of `Foo` with my lens.

I was hoping that 
```scala
@Lenses
case class Foo[A,B](m1: Map[(A,B),Double], m2: Map[(A,B),Long], d1: Double, d2: Double)
```
would produce something equivalent to:
```scala
object Foo {
  def m1[A,B] = Lenser[Foo[A,B]](_.m1)
  def m2[A,B] = Lenser[Foo[A,B]](_.m2)
  def d1[A,B] = Lenser[Foo[A,B]](_.d1)
  def d2[A,B] = Lenser[Foo[A,B]](_.d2)
}

**Comment by julien-truffaut** [comment]
at the moment `@Lenses` is generating val, the long term goal would be to produce vals for `Lens` and methods for `PLens`, e.g.
```scala
@Lenses
case class Point(x: Int, y Int)

// generates 
object Point {
  val x: Lens[Point, Int] = ...
  val y: Lens[Point, Int] = ...
}

@Lenses
case class Foo[A,B](a: Double, b: Double)

object {
  def a[A, B, C]: PLens[Foo[A, B], Foo[C, B], A, C] = ...
  def b[A, B, C]: PLens[Foo[A, B], Foo[A, C], B, C] = ...
}
``` 

To be honest, I only have a superficial knowledge of macro @adamw or @dwijnand would have a better idea of the complexity of the work involved.

**Comment by refried** [comment]
That makes sense about the current `val` implementation.

Are you sure that `PLens` makes sense here?  To me it doesn't;  is it possible we are talking about two different things?  Can you use my `Foo2` (I renamed it just now, to be unique for discussion) in your example of what you envision `@Lenses` generating?  Would it traverse the whole `Map`? I don't even know what it would mean.

To me it would be very valuable to be able to generate `Lens` for a parametric type (`def m1[A,B]: Lens[Foo2[A,B],...]`.  If `PLens` achieves the same thing, I guess that's fine (I don't understand it) except that it's going to trip people like me up.

**Comment by julien-truffaut** [comment]
I updated my example, it was incorrect `Foo` (I renamed it to `Bar`) was supposed to have accessors using type parameters. In fact, your example is even more complex because `Foo2` have accessors that use 2 type parameters (`m1` and `m2`).

Sorry I digress from your original question, the bottom line is that it should be possible to generate them automatically but we haven't found the time to do it. If anyone wants to give it a try, I would be glad to help.

ps: `Lens[S, A]` is just a type alias for `PLens[S, S, A, A]`, basically a `PLens` can modify the type of the target of a lens. For example, you can have a `PLens` to the first element of a `Tuple2`:
```scala
def first[A, B, C]: PLens[(A, B), (C, B), A, C] = ...
first.modify( _.toString )( (1, "Hello") ) == ("1", "Hello")
``` 
but if you define `first` as a `Lens` you can only modify the value and not the type: 
```
def _first[A, B]: Lens[(A, B),  A] = ...
_first.modify(_ + 1)( (1, "Hello") ) = (2, "Hello")
_first.modify( _.toString )( (1, "Hello") ) // does not compile
```
