### ISSUE TITLE
Add the `ala` set of functions for isomorphisms

### ISSUE THREAD

**Issue by NightRa** [julien-truffaut/Monocle#185]
Add the `ala` set of functions for isomorphisms.
Also, it would need iso's to be defined for the newtypes for which we would like to use this on.
For example: ```ala Endo foldMap```

**Comment by julien-truffaut** [comment]
can you give the type signature of `ala`?

**Comment by puffnfresh** [comment]
:+1: 

```haskell
ala :: Wrapped s s a a => (s -> a) -> ((s -> a) -> e -> a) -> e -> s
```

**Comment by puffnfresh** [comment]
> As with wrapping, the user supplied function for the newtype is ignored.

In Haskell, that's for inference reasons. I recommend leaving that off for a Scala version because we'll probably have to give explicit types parameters for most uses, anyway.

**Comment by julien-truffaut** [comment]
Following recent discussion in https://github.com/julien-truffaut/Monocle/pull/365, I think we can close this issue. It is unlikely we can get good type inference in function like `ala` in scala
