### ISSUE TITLE
Update @Lenses documentation in Readme 

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#189]
intellij support + @refried extension for case classes with type parameters

**Comment by refried** [comment]
I was gonna tackle this today, but still having some IntelliJ inference issues with macro lenses with type parameters.  Do we need to do a binary release before Mikhail can address the issue?  Or what do you think about this?

![screen shot 2015-02-25 at 2 31 00 pm](https://cloud.githubusercontent.com/assets/538571/6378871/2191eb3a-bcfc-11e4-8a02-134a92296422.png)

**Comment by julien-truffaut** [comment]
I don't think the extension of the macro you wrote is supported by intellij. They are actually hardcoding the code of the macro (e.g. if annotation == monocle.macro.Lenses then ...), so we will need to ask them to update to support it.

**Comment by refried** [comment]
Wow, really?  Ok so what's the next step.  Should I just update the intellij issue and point them to Monocle/master ?

**Comment by julien-truffaut** [comment]
I suppose we should first confirm that they support correctly the macro for case classes without type parameters (was your screenshot using the latest version?). Then we can create a new ticket for the extension or ask them what do they prefer.

**Comment by refried** [comment]
Yes, screenshot was using the latest version afaik.  It is scala plugin v1.3.2.26.EAP  

`@Lenses` for case classes without type parameters look good to me, although I'm basing that conclusion on the monocle-example project, LensExample file;  not another custom projects.

Even the new `@Lenses` look good in isolation:
![screen shot 2015-02-25 at 3 16 17 pm](https://cloud.githubusercontent.com/assets/538571/6379583/6d0bb064-bd01-11e4-99f6-6b3d72b76323.png)

![screen shot 2015-02-25 at 3 17 50 pm](https://cloud.githubusercontent.com/assets/538571/6379596/81ccb4ee-bd01-11e4-82de-63af6141e5b0.png)

but there is something unusual happening once `applyLens` is added to the mix.

P.S. I don't know why `Wow` appears deprecated.

**Comment by refried** [comment]
Wait, sorry; I just noticed it's showing `Lens[Bar,X]` instead of `Lens[Bar[X],X]`

**Comment by refried** [comment]
So the "actual" type a few comments back is wrong; should be `Lens[Foo[Int,Symbol],Double]`, not `Lens[Foo,Double]`, or at least some kind of `[A,B]Lens[Foo[A,B],Double]`.

**Comment by refried** [comment]
I let him know here: https://youtrack.jetbrains.com/issue/SCL-7419#comment=27-929107

**Comment by julien-truffaut** [comment]
Thanks @refried for updating intellij ticket :)

I updated Lens example by removing the use of syntax (i.e. `applyLens`) and I added a composition example. At this line https://github.com/julien-truffaut/Monocle/blob/master/example/src/test/scala/monocle/LensExample.scala#L87 , I can see an intellij error 
```
Type mismatch, expected: Foo, actual: Foo[Int, Symbol]
```

Hopefully, it should disappear once they implement your extension.

**Comment by refried** [comment]
I like the new object names.

**Comment by julien-truffaut** [comment]
cool, do you think we should use these terms `Manual`, `Semi-Automatic`, `Automatic` in the readme?

**Comment by refried** [comment]
Hm... let me see if I can come up with something I like better, but I think it would be ok.  Btw I also just noticed and like how `GenLens` avoids the need for instantiating a `Lenser`.

Also, I was thinking it would be good if the `val` and `def` lenses were seamlessly part of the same example in the readme, instead of having a "no parameters" example and a separate "type parameters" example.  But I am drawing a blank on where to add a type parameter to the current example.

**Comment by julien-truffaut** [comment]
`GenLens` is just an alias for `Lenser`, we wanted some consistency between all generator (.i.e. `GenLens`, `GenPrism`, `GenIso`). `Lenser` will be deprecated in the next release.

I am wondering if it will not be easier to have a `GenOptic` object with methods `genLens`, `genPrism`, `genIso`.

**Comment by refried** [comment]
I don't see much difference between 3 apply methods vs 3 gen methods, but I guess it's subjective, so we'd need to get some users and see what they think.

**Comment by NightRa** [comment]
@julien-truffaut I prefer the upper case names. Also no need to prefix or import GenOptic.
