### ISSUE TITLE
Macro does not work outside of monocle package

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#190]
```scala
package foo
import monocle.macro.GenLens
case class Foo(n: Int)
object Foo {
  val lens = GenLens[Foo](_.n)
}
```

causes:

```
Error:(23, 18) constructor PLens in class PLens cannot be accessed in <$anon: monocle.PLens[foo.Foo,foo.Foo,Int,Int]>
  GenLens[Custom](_.value)
                 ^
```

I suppose the problem is that macro use the call site to determine package visibility. Since `Lens` constructor is private to monocle, it cannot generate lenses outside of monocle package :/

Thanks for @refried for finding this.

**Comment by refried** [comment]
wait, don't merge yet
