### ISSUE TITLE
Upgrade shapeless dependency

### ISSUE THREAD

**Issue by pomadchin** [julien-truffaut/Monocle#194]
Is it possible to make smth with shapeless version?
Mb, as a variant, to publish and support two versions of Monocle, with different shapeless versions, or to scope it in a some way, to make not in conflict with other shapeless versions? Would be great!

**Comment by julien-truffaut** [comment]
I am sure it is possible but I would like to understand your use case. 
shapeless is only a dependency of monocle-generic module, I am fine to upgrade the version of shapeless in the next release.

**Comment by pomadchin** [comment]
Oh, did not noticed that only in monocle-generic it helped; previously included all components of monocle (played with lens).
Case: actively using monocle lens and shapeless in a play framework project, got lots of generic shapeless code, and of course it is interesting to try new shapeless improvements. 
It was just a depency-question. :) Thx for reply!

**Comment by julien-truffaut** [comment]
For the moment, I see `monocle-generic` as a play ground to experiment shapeless - monocle combination but it is really optional. You should find most of what you want in `monocle-core`.

If you don't mind I will keep this issue open to remind me to upgrade shapeless.

**Comment by julien-truffaut** [comment]
will probably postpone until shapeless 2.12 is released

**Comment by julien-truffaut** [comment]
I upgraded to shapeless 2.2.0
