### ISSUE TITLE
Lens benchmark in Wiki is hard to read

### ISSUE THREAD

**Issue by geggo98** [julien-truffaut/Monocle#196]
I had problems interpreting the data in the lens benchmark in the wiki. I took the raw data and formatted them myself. I think my visualization will help others, so perhaps you want to include it in the wiki:

![image](https://cloud.githubusercontent.com/assets/54929/6670569/9ad7ba6c-cbff-11e4-86a4-2a53def2492f.png)

**Comment by geggo98** [comment]
You can find the sources for the image in my [OneDrive](https://onedrive.live.com/redir?page=view&resid=E74A497D5D2F9100!320&authkey=!AEdypbF1QBVpuqU) (direct download of XLSX file, no sign-in needed).

**Comment by julien-truffaut** [comment]
Thanks Stefan, it is indeed helpful! Do you think we could instead display an histogram grouped by method with different color? If yes, would it be possible to automate that process?

**Comment by julien-truffaut** [comment]
The histograms are really good, do you know how can I export them in an picture? I only found how to get a pdf

**Comment by geggo98** [comment]
I'll have a look on it. The excel visualization was a quick job during a boring meeting. For automation I think on D3.js or even better Scala.js, reading the raw data from the web site and rendering directly on the page as SVG. Shouldn't be too hard.

**Comment by julien-truffaut** [comment]
close for #376
