### ISSUE TITLE
Setter (semigroupy) composition

### ISSUE THREAD

**Issue by japgolly** [julien-truffaut/Monocle#213]
Would this be useful as a PR?

I wrote this to compose `PSetter`s. (I initially thought to do it with `PTraversal` but I think we'd need to widen the `Applicative` constraint to `Monad` to get `join`.)

```scala
  implicit class SetterExt[S, A, B](val x: PSetter[S, S, A, B]) extends AnyVal {
    def merge(y: PSetter[S, S, A, B]): PSetter[S, S, A, B] =
      PSetter(f => y.modify(f) compose x.modify(f))
  }

  def compositeSetters[S, A, B](h: PSetter[S, S, A, B], t: PSetter[S, S, A, B]*): PSetter[S, S, A, B] =
    t.foldLeft(h)(_ merge _)
```

**Comment by julien-truffaut** [comment]
sounds interesting, a few questions:
*   is it possible to have a `PSetter[S, S, A, B]` where `A != B`? if no then lets use `Setter[S, A]`
*   how do you think this relate to `SemiGroup[Endo]`? After all, `modify(f)` is an `Endo[S]`

**Comment by julien-truffaut** [comment]
more I think about it, more it looks like this composition forms another `Category` for optics where the `zero` is the optics that does does not point to any value. In facts, this can be generalised to `Prism` (and so `Optional`, `Traversal`, `Setter` and `Fold`), e.g.:

```scala
def zero[S, A]: Prism[S, A] = Prism(_ => Option.empty[A])(identity)
```

**Comment by julien-truffaut** [comment]
from haskell lens irc, composing `Setter` horizontally (as suggested here) is unsound in case they overlap, for example:
```scala
val s1, s2 = Setter.id[Int]
def inc(n: Int): Int = n + 1
def neg(n: Int): Int = -n

(s1 merge s2).modify(inc . neg) 
  == s1.modify(inc . neg) andThen s2.modify(inc . neg) 
  == neg(_) + 1 andThen neg(_) + 1
  == neg(neg(_) + 1) + 1
  == identity

(s1 merge s2).modify(inc) . (s1 merge s2).modify(neg) 
  == (s1 merge s2).modify(inc)
  == _ + 2
```

**Comment by japgolly** [comment]
Sorry for my neglect on this one. I did plan to be more useful :) Your conclusion is very reasonable.
