### ISSUE TITLE
Release a version for Scala 2.12-RC2

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#216]

**Comment by julien-truffaut** [comment]
blocked on https://github.com/typelevel/discipline/issues/16 which in turns is blocked on scpec2 and scalacheck upgrade

**Comment by SethTisue** [comment]
ping?

**Comment by julien-truffaut** [comment]
@SethTisue I was planning to wait for RC2 and shapeless release to release all monocle modules at once. If you need `monocle-core` for RC1, I can give it a try tonight.

**Comment by SethTisue** [comment]
I deleted my comment because I'd forgotten about #397 :-)

to help us QA RC1, it would be good if you at least had a WIP branch that builds monocle-core, just so you can let us know about any regressions. but for actually publishing, waiting for RC2 seems fine.

**Comment by julien-truffaut** [comment]
Np, I pushed `scala-2.12-RC1-core`. `core` compiles with RC1

**Comment by SethTisue** [comment]
once Shapeless publishes for RC2, I hope you will too

**Comment by julien-truffaut** [comment]
sure, I am waiting for it. Please don't hesitate to ping me if I miss the announcment

**Comment by SethTisue** [comment]
Shapeless 2.3.2 for 2.12.0-RC2 is on Maven Central now.

**Comment by julien-truffaut** [comment]
depend on https://github.com/non/kind-projector/issues/39
