### ISSUE TITLE
Product for arbitrary lenses

### ISSUE THREAD

**Issue by AlexeyRaga** [julien-truffaut/Monocle#224]
I see that there is a `product` function for `PLens`, but what about the ability to create a product of two arbitrary lenses?
Say, POptional and PTraversal? Is it possible?

**Comment by julien-truffaut** [comment]
There is a product for getter and iso,  we should check if it is possible to implement it for other optics and verify that implementation is lawful. 

If you want to give it a try for optional,  I and other contributors will be happy to review it :-)
