### ISSUE TITLE
Testing Monocle on Android.

### ISSUE THREAD

**Issue by wpoosanguansit** [julien-truffaut/Monocle#225]
Hi,

I am not sure if the library can be used on Android.  I tested it out and I do have 2 errors which I am not sure how to resolve.  Firstly, there seems to be conflict with org.json4s.scalaz classes.  It just complains that Functor is not a function of org.jason4s.scalaz.  And the second error is as below:

22:25:59.660 [ERROR] [system.err] 22:25:59.657 [ERROR] [org.gradle.api.internal.tasks.scala.ZincScalaCompiler] /Users/watt/Desktop/Projects/AndroidStudio/HelloScala/app/src/main/scala/com/company/helloscala/MainActivity.scala:90: value _age is not a member of object MainActivity.this.Cat
22:25:59.664 [ERROR] [system.err] 22:25:59.663 [ERROR] [org.gradle.api.internal.tasks.scala.ZincScalaCompiler]   Cat._age.get(alpha)
22:25:59.665 [ERROR] [system.err] 22:25:59.665 [ERROR] [org.gradle.api.internal.tasks.scala.ZincScalaCompiler]       ^
22:26:00.457 [ERROR] [system.err] 22:26:00.457 [ERROR] [org.gradle.api.internal.tasks.scala.ZincScalaCompiler] one error found

I am guessing that there should be some proguard rule to retain the class but I am just not sure what it should be.  I have tried it with:

-keep class monocle.** {  *; }

But that still does not resolve the issue.  Within the the code itself, I do see Cat._age in code completion.  And the code does compile fine.  Thanks for your help.

**Comment by julien-truffaut** [comment]
I am sorry, I am not familiar with android build but maybe some one else is. Let's see.

**Comment by wpoosanguansit** [comment]
Thank you for your help.  I think I found the issue.  Turns out that gradle does not support macro plugin yet.  So the compilation was not complete.  Thanks again.
