### ISSUE TITLE
implicit lenses

### ISSUE THREAD

**Issue by drdozer** [julien-truffaut/Monocle#232]
Many of my case-classes have fields that each have unique types. I have a bunch of generic operations over individual fields and I'd like to be able to implicitly lift them over the case class. To do this at the moment, I manually lift them with the lens for the field. However, if the lenses were implicit, I could write this lifting code once and have it discover the right lens implicitly.

Could we have an option to the lens annotation to make the generated lenses implicit? That would cut out a whole world of biolerplate I'm currently writing. The only other way I can fix it is to manually create the lenses and store them in implicits in the companion object of the case class, but this is also brittle biolerplate.

**Comment by julien-truffaut** [comment]
I don't think generated `Lenses` should be defined as implicit for two reasons:

*    `@Lenses` is already doing a lot and I would prefer not to complicate it
*     I believe that implicit should be globally unique and reserved to type class instances, `Lens` or other `Optics` are not a type class

I could be convinced to mark them as implicit if someone can convince me (on the second point in particular).

**Comment by NightRa** [comment]
@julien-truffaut Pointed out why this is problematic and I agree, 
So it will probably not happen.
Can we close the issue?

**Comment by drdozer** [comment]
Yes. We can close this. I need to write up a related abstraction which does
have typeclass instances which can be used to summon the required lens.
