### ISSUE TITLE
Defining an optic that modifies the source

### ISSUE THREAD

**Issue by drbild** [julien-truffaut/Monocle#240]
Is there a standard way to combine two lens into one that modifies, rather than decomposes, the source structure. E.g, for an arbitrary `at: Iso[S,A]`, instead of modifying directly as

`at.modify(a1 => a2)(s_a1) =  s_a2`
    
instead define a combinator `modifyAt`

`modifyAt(at: Iso[S,A])(map: Iso[A,A]): Iso[S,S]`  

such that the returned `i: Iso[S,S]` has `i.get(s_a1) = s_a2` and `i.reverseGet(s_a2) = s_a1`.

I've defined such combinators under the names `map{Iso,Prism,Lens,Optional}` in this [gist](https://gist.github.com/drbild/89aff7334ef3a351e505).
I'm wondering if this concept is already available somewhere or is considered bad practice for some reason.

**Comment by julien-truffaut** [comment]
I believe `mapIso` is correct because we could always implement it as:
```scala
def mapIso[S, A](selection: Iso[S, A], f: Iso[A, A]): Iso[S, S] =
  selection composeIso f composeIso selection.reverse
```

For the other ones, we should ideally prove that they satisfy the laws.

**Comment by drbild** [comment]
`mapPrism` is straightforward to prove, but I haven't considered the others yet. (They're trivially for true for the particular S and A in my specific use case.)

Do you have any potential interest in including those that do satisfy the laws?  If so, I'll try to make time to work on a PR.

As you allude to, it'd be nice to (be able to) implement these via composition, to get the laws for free.  I don't think that is currently possible, but perhaps there is a more-primitive combinator to add that would then give us these for free.

**Comment by julien-truffaut** [comment]
what I am wondering is what sort of `Lens[A, A]` or `Prism[A, A]` could write that is not an `Iso`. In particular, I am almost sure you cannot write a lawful `Prism[A, A]` that is not an `Iso`.

Do you have a concrete example by any chance?

**Comment by drbild** [comment]
You're correct.

I'm defining optics to transform recursive data structures.

Take manipulating json as a concrete example. Some APIs have spurious structure: `{ "widgets" : { "value" : [...] } }` instead of just `{ "widgets" : [...] }`.  Sometimes a child needs to be moved to a different parent. Or completely removed, being restored only before sending data back to the API.

However, the type system doesn't capture the actual change in structure, so you end up with a `Lens[A,A]` and an implied restriction on the inhabitants of the "second" `A`.  Generally I control the values of the "second" `A`, but not the first, so abusing `Prism[A, A]` and `Optional[A, A]` is convenient too.

Sounds like optics aren't a good fit for this.

**Comment by julien-truffaut** [comment]
for the first transformation you mentioned, `{ "widgets" : { "value" : [...] } } to { "widgets" : [...] }` it seems that we can encode it in an `Iso[Json, Json]`. In that case you could do:
```scala
val trans: Iso[Json, Json] = ...
def yourLogic(json: Json): Json = ... // here it expects { "widgets" : [...] }
trans.modify(yourLogic) // modify will apply the transformation inverse and produce a Json with   `{ "widgets" : { "value" : [...] } } 
```

The problem is then how to easily construct `trans`, maybe that what you wanted to do with `composeLens`?

**Comment by drbild** [comment]
Exactly.

In this case `trans` is bijective on `Json` values of the expected form, but what to do with unexpected forms?  I don't see a way to satisfy the `Iso` laws there.

**Comment by drbild** [comment]
I had initially misunderstood the `Prism`/`Optional` variants, and thought they worked.  But the `put` direction is actually still required to succeed.
