### ISSUE TITLE
Formalise / document process

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#249]
It would be nice to have some documentation explaining how do we contribute / code review / version / release etc ... Basically, something like https://github.com/non/cats/blob/master/PROCESS.md

I believe we are not enough maintainers to ask for one sign-off for all changes. Maybe we could relax to:
*   all changes should be done via pull requests (i.e. no commit to master directly)
*   *major* PR require a :+1: for at least another maintainer. By major I mean a non binary compatible change or a significant addition (e.g. new module / typeclass)
*  *minor* contribution can be merged without :+1: if no one commented on the PR after 1 day??? 

All inputs are greatly appreciated, in particular but not only from @aoiroaoino and @NightRa

**Comment by NightRa** [comment]
:+1: from me.
This has generally worked great up until now.
Doing everything via PRs notifies me on every change and gives chance for code reviews, which I really like :smiley:

**Comment by aoiroaoino** [comment]
Looks good to me :+1:
