### ISSUE TITLE
add learning resources to the website

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#251]
e.g. links toward slides, blog posts, presentation

**Comment by julien-truffaut** [comment]
I propose that we also make sections for resources in different languages than english, I know that @aoiroaoino or @1ambda have some blog posts for example.

**Comment by 1ambda** [comment]
@julien-truffaut 

I recently posted Monocle tutorial written in Korean ([Scala Lens Library, Monocle](http://1ambda.github.io/scala-monocle-tutorial/)). If you don't mind, I would like to add it to *learning resource section*

**Comment by julien-truffaut** [comment]
great I will add it

**Comment by aoiroaoino** [comment]
Please feel free to use my informations.

#### My blog posts written in Japanese.

- [Introduce of Monocle](http://aoino.hatenablog.com/entry/2014/12/23/050932)
  (but, this contents is a little old...)
- [ApplyXXX Usage](http://aoino.hatenablog.com/entry/2015/06/15/012432)

#### Other Optics Libraries

- Scala
 - https://github.com/jrudolph/json-lenses
 - https://github.com/adamw/quicklens
- Scala (maybe, inactive)
 - https://github.com/gseitz/Lensed
 - https://github.com/retronym/macrocosm
 - https://github.com/akisaarinen/rillit
 - https://github.com/travisbrown/rillit
 - https://github.com/hexx/lenser
 - https://github.com/gseitz/Lensed

**Comment by NightRa** [comment]
@1ambda @aoiroaoino @julien-truffaut I say we should add sections for Japanese and Korean, seperated from the other sections.

**Comment by NightRa** [comment]
@aoiroaoino I don't think all of these are nessesary. We should include the ones that are used and  maintained.

**Comment by aoiroaoino** [comment]
> We should include the ones that are used and maintained.

yep, I think so, too.
