### ISSUE TITLE
Create date optics

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#260]
e.g.

``` scala
type Minute = Int Refined Interval[W.`0`.T, W.`59`.T]

val minute: Lens[Date, Minute] = ???

minute.set(30: Minute)(d)   // ok
minutes.set(79: Minute)(d) // compile error
```

see https://github.com/fthomas/refined/issues/63

**Comment by julien-truffaut** [comment]
require https://github.com/fthomas/refined/pull/51

**Comment by fthomas** [comment]
FYI: refined 0.3.0 has been released for Scala 2.10 and 2.11.

If there is anything else I can help with, ping me. :-)

**Comment by julien-truffaut** [comment]
@fthomas cheers!

**Comment by julien-truffaut** [comment]
Can we define a lawful optic for days since the number of days in a month depends on the month and some times year?

```scala
type Day = Int Refined Interval[W.`0`.T, W.`???`.T]
val day: Lens[Date, Day] = ???
```
