### ISSUE TITLE
Lens benchmark instructions out of date

### ISSUE THREAD

**Issue by note** [julien-truffaut/Monocle#261]
Instead of:
```
sbt
project monocle-bench
monocle-bench/run -rf=csv .*Lens.*
```

I think should be:

```
sbt
bench/jmh:run -rf=csv .*Lens.*
```

Such commands worked on my machine. I wanted to prepare PR with that but it's wiki page which is in a separate repo which does not have PR model AFAIK.

**Comment by julien-truffaut** [comment]
good point, I will update the wiki.

You might be interested by an experiment I am doing on a separate project: https://github.com/julien-truffaut/LensImpl/blob/master/bench/src/main/scala/lensimpl/bench/Main.scala

Ideally I would like to automatically generate a matrix that compare `Monocle` impl versus vanilla scala and maybe other impl. We might also want to put benchmarks on the website
