### ISSUE TITLE
add safe down cast for BigDecimal

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#266]
e.g. `Prism[BigDecimal, Double]`,  `Prism[BigDecimal, Int]` etc ...

**Comment by julien-truffaut** [comment]
watch out issues in https://github.com/argonaut-io/argonaut/issues/196

**Comment by NightRa** [comment]
Do we actually know if it's a problem with the toString or the toLong?

**Comment by julien-truffaut** [comment]
it is from `toLong` because we discovered the issue in Argonaut running `PrismTests`

https://travis-ci.org/argonaut-io/argonaut/builds/84583020

**Comment by NightRa** [comment]
These universal property tests are so awesome.
I don't believe such a thing would have been found otherwise.

**Comment by julien-truffaut** [comment]
Definitely!

**Comment by NightRa** [comment]
The problem seems stems from ```-1.92502709527405133E18``` being too large for doubles to hold in full precision.

**Comment by NightRa** [comment]
Double's maximal stable integer range is ```[-2^53,2^53 - 1]``` and this one is out of this range. It's between -2^60 to -2^61.

**Comment by julien-truffaut** [comment]
interesting but it seems that the same behaviour happens for `toLongExact`

```scala
BigDecimal(-1.92502709527405133E18).toLongExact == -1925027095274051330
```

even though `toLongExact` doc says:
```
 /** Converts this `BigDecimal` to a [[scala.Long]], checking for lost information.
    * If this `BigDecimal` has a nonzero fractional part, or is out of the possible
    * range for a [[scala.Long]] result, then a `java.lang.ArithmeticException` is
    * thrown.
    */
```

**Comment by NightRa** [comment]
One solution would be to check for the safe integer bounds when converting from a double to an int.

**Comment by NightRa** [comment]
This information is lost in the construction of the BigDecimal.
