### ISSUE TITLE
add Maven central badge

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#268]
e.g. https://github.com/fthomas/refined or https://github.com/http4s/http4s

**Comment by aoiroaoino** [comment]
Do you use this?
https://github.com/jirutka/maven-badges

**Comment by julien-truffaut** [comment]
right that the one I meant

**Comment by fthomas** [comment]
You can just use https://img.shields.io/maven-central/v/com.github.julien-truffaut/monocle_2.11.svg:

![Badge](https://img.shields.io/maven-central/v/com.github.julien-truffaut/monocle_2.11.svg)

**Comment by julien-truffaut** [comment]
@fthomas thanks
