### ISSUE TITLE
add left and righ for optics

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#269]
e.g.

```scala 
abstract class PIso[S, T, A, B]{
  final def left[C] : PIso[S \/ C, T \/ C, A \/ C, B \/ C] = ...
  final def right[C]: PIso[C \/ S, C \/ T, C \/ A, C \/ B] = ...
}
```

**Comment by julien-truffaut** [comment]
I am wrong `Iso` cannot be a `ProChoice` because it is not a `ProFunctor`. We can still define `left` and `right`

**Comment by NightRa** [comment]
Or rather it has 2 profunctor instances which both are inherently required for it to be an iso?

**Comment by julien-truffaut** [comment]
how do you define `dimap` or even `mapfst` for an `Iso`? 

```scala
def mapfst[A, B, C](iso: Iso[A, B])(f: C => A): Iso[C, B] 
  // we need an `Iso[C, A]` but we only have a `C => A`
```

**Comment by julien-truffaut** [comment]
I started some work on https://github.com/julien-truffaut/Monocle/tree/left-right

It is possible to implement a `left` and `right` for `Lens` but I have the feeling it will break the laws, I need some time to think it through
