### ISSUE TITLE
Document limitations related to SI-7139

### ISSUE THREAD

**Issue by travisbrown** [julien-truffaut/Monocle#280]
This kind of thing surprises me every time I run into it, and I've run into it many, many times in various projects:

```scala
scala> monocle.Iso.id[String]
res0: monocle.Iso[String,String] = monocle.PIso$$anon$12@108bda9e

scala> monocle.Iso.id[String]
<console>:11: error: value id is not a member of object monocle.Iso
       monocle.Iso.id[String]
                   ^
```

(This issue is also noted in #231.)

Since there's no indication that [SI-7139](https://issues.scala-lang.org/browse/SI-7139) will get resolved anytime soon, it might be worth adding a note to the README about the limitations of using `Iso`, `Optional`, etc. in the REPL.

**Comment by julien-truffaut** [comment]
Thanks for the reference, I had no idea where the issue came from! 

Your right, we should add a note in the Readme and / or website

**Comment by justjoheinz** [comment]
Hmm, that explains why I sometimes banged my head against the wall trying to use `tut` for the tutorials/documentation.

**Comment by puffnfresh** [comment]
Haha, Scala :rainbow:
