### ISSUE TITLE
Plated optic

### ISSUE THREAD

**Issue by puffnfresh** [julien-truffaut/Monocle#288]
I'd like to see the [Plated type-class](https://hackage.haskell.org/package/lens-4.13/docs/Control-Lens-Plated.html#g:1) from Haskell lens implemented in Monocle:

```scala
trait Plated[A] {
  def plate: Traversal[A, A]
}

object Plated {
  def plate[A: Plated]: Traversal[A, A] = implicitly[Plated[A]].plate
  def children[A: Plated](a: A): List[A] = plate[A].getAll(a)
  def universe[A: Plated](a: A): Stream[A] = {
    val fold = plate[A].asFold
    def go(b: A): Stream[A] = fold.foldMap[Stream[A]](c => c #:: go(c))(b)
    go(a)
  }
  def transform[A: Plated](f: A => A)(a: A): A = plate[A].modify(f)(a)
}
```

The above might be a good start but I'd love to see functions like `rewrite`.

Some questions have to be answered, though, for example: Stream makes sense for `universe` but it might also make sense for `children` - what should we do?

**Comment by julien-truffaut** [comment]
Good idea, I guess we should be consistent for the return type. So `Stream` is probably best. If user wants a `List`, it is always possible to use `plate.getAll`
