### ISSUE TITLE
Iso macro for case class ↔ tuple

### ISSUE THREAD

**Issue by japgolly** [julien-truffaut/Monocle#295]
Might be an idea to have `GenIso` create isos between case classes and their product tuples.

Eg. an `Iso[X, (Int, String)]` for a `case class X(i: Int, s: String)`

**Comment by japgolly** [comment]
Macro translation: ∀ A.
```scala
Iso((a: A) => A.unapply(a).get)((A.apply _).tupled)
```

**Comment by NightRa** [comment]
You can currently do this with `monocle-generic` via shapeless.
https://github.com/julien-truffaut/Monocle/blob/master/generic/src/main/scala/monocle/generic/Product.scala

**Comment by julien-truffaut** [comment]
@japgolly is it an acceptable solution for you?

**Comment by japgolly** [comment]
Hi guys. Thanks @NightRa for the idea but it would be preferable to be able to do this without Shapeless. Many projects use it but also many avoid it as it, at least, has the perception of being quite heavyweight.

Because that little one-liner I wrote above is all that's needed without any dependencies, I think it would be useful to include in Monocle core. WDYT? I'd be happy to submit a PR if you're accepting of the idea.

**Comment by puffnfresh** [comment]
@japgolly I agree :+1:

**Comment by aoiroaoino** [comment]
:+1:

**Comment by japgolly** [comment]
Alrighty! I'll get on in...

**Comment by NightRa** [comment]
We should think where should we draw the line in what macros should we have.
A possible concern I have is that of IDE support; Intellij currently supports the @Lens macro specifically. One thing that may keep orgs/ projects from using monocle with macros is red errors all over their code.
Intellij recently opened an API for supporting external macros, with an example of the built in @Lens macro support for monocle.
So as I see it, each new macro would need 2 Implementations to go with it; The macro itself in the Monocle project, and the Intellij support via their APIs. (duplicate definitions to keep in sync, not so fun). Should either be all in or nothing.
Being in the middle is no good place to be IMO - As if there was no IDE support.

What do all of you think?

**Comment by japgolly** [comment]
It would seem strange to me to decline useful behaviour because it will
cause a highlighting problem in one of the available IDEs, one which
already has loads of highlighting problems anyway.

I don't mean to sound dismissive of your concern. I think how that concern
is addressed should be considered, sure, but omitting useful behaviour
should be at the very, very bottom of the list.

That's my 2 cents.
​

**Comment by japgolly** [comment]
I've completed this on my branch (I thought we were already cool to add this).
https://github.com/japgolly/Monocle/commit/b22e28a1198b66eec2d1a394d81b894183bf45ba

I'll hold off on a PR until we're all happy. Feel free to send me early feedback.

**Comment by julien-truffaut** [comment]
The good points that I see with @japgolly proposition:
    - it can generalise `GenIso.apply` and maybe `GenIso.unit`
    - will be supported by IDE based on presentation compiler such as scala IDE
    - potentially faster than shapeless version (need some benchmarks)

On the cons side:
    - require some additional work to be supported on intellij :(
    - whitebox macro are more difficult to understand because the return type is not explicit

So I would be for adding `GenIso.fields` if we create a separate issue to add intellij support for it (and deprecate `GenIso.apply` when it is done). 

Bonus would be to run a quick benchmark (doesn't need to be committed) to compare `productToTuple` and `GenIso.fields`

**Comment by NightRa** [comment]
:+1:

**Comment by NightRa** [comment]
@japgolly Go on with your PR :)
IDE support for anything other than @Lens isn't there anyway, so that's definitely for another unrelated discussion, whether we should work on the support of that too.

**Comment by japgolly** [comment]
Ok understood and thanks @NightRa and @julien-truffaut . I'll open a PR now.
