### ISSUE TITLE
Remove last mentions of matching

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#296]

**Comment by NightRa** [comment]
We reverted to `getOrModify` from `matching` :)
Just need to correct the replaced `matching -> getOrModify` in some of the comments by this commit: c5f6c17db1dc62e6855d9a041e3e316bc5ca570a

**Comment by julien-truffaut** [comment]
I don't see any mention of `matching` anymore

**Comment by NightRa** [comment]
```return empty if the [[POptional]] is not getOrModify``` should be ```return empty if the [[POptional]] is not matching```
And so on.

**Comment by julien-truffaut** [comment]
right! I was looking in the other way around
