### ISSUE TITLE
monocle.function.Plated isn't in 2.10 version of 1.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by jedws** [julien-truffaut/Monocle#306]
see this failed build:

https://travis-ci.org/argonaut-io/argonaut/jobs/95055414

haven't had time to diagnose yet

**Comment by puffnfresh** [comment]
Plated is only a few weeks old, might be an old SNAPSHOT.

**Comment by julien-truffaut** [comment]
it seems that the snapshot auto publish is only working for 2.11. I manually republished snapshot and restarted argonaut build, now it is green :)

**Comment by jedws** [comment]
legend, thanks!
