### ISSUE TITLE
{A→Op B, B → Op A} - thoughts?

### ISSUE THREAD

**Issue by japgolly** [julien-truffaut/Monocle#325]
I wonder, what are your thoughts on an optic for the intersection of two larger types like this:
```
A → Option B
B → Option A
```

It's like a prism where both sides can be optional. `Optional` itself doesn't cut it. It can accurately be modelled as `Iso[Option[A], Option[B]]` but I feel like a more specialised abstraction should or may already exist. Something like `Intersection[A, B]`.

Have thee thoughts, ye experts?

**Comment by japgolly** [comment]
Btw, this is what I whipped up for my own purposes.

```scala
abstract class Intersection[A, B] {
  val getOption: A => Option[B]
  val reverse: Intersection[B, A]

  def get(a: A, default: => B): B =
    getOption(a).getOrElse(default)

  def fold[C](a: A, f: B => C)(default: => C): C =
    getOption(a).fold(default)(f)

  def composeIntersection[C](that: Intersection[B, C]): Intersection[A, C] =
    Intersection[A, C](getOption(_) flatMap that.getOption)(that.reverse.getOption(_) flatMap reverse.getOption)

  final def toIso: Iso[Option[A], Option[B]] =
    Iso((_: Option[A]) flatMap getOption)(_ flatMap reverse.getOption)

  final def toPrism: Prism[Option[A], B] =
    Prism((_: Option[A]) flatMap getOption)(reverse.getOption)
}

object Intersection {

  private final class Id[A] extends Intersection[A, A] {
    override val getOption                                              = Some(_: A)
    override val reverse                                                = this
    override def get                (a: A, default: => A)               = a
    override def fold               [C](a: A, f: A => C)(default: => C) = f(a)
    override def composeIntersection[C](that: Intersection[A, C])       = that
  }

  private[this] val idInstance = new Id[Any]

  def id[A]: Intersection[A, A] =
    idInstance.asInstanceOf[Id[A]]

  def apply[A, B](f: A => Option[B])(g: B => Option[A]): Intersection[A, B] = {
    lazy val ab: Intersection[A, B] =
      new Intersection[A, B] {
        override val getOption = f
        override val reverse = new Intersection[B, A] {
            override val getOption = g
            override val reverse = ab
          }
      }
    ab
  }

  def fromPrism[A, B](p: Prism[A, B]): Intersection[A, B] =
    apply(p.getOption)(b => Some(p reverseGet b))

  def fromIso[A, B](i: Iso[A, B]): Intersection[A, B] =
    apply[A, B](a => Some(i get a))(b => Some(i reverseGet b))
}
```

**Comment by julien-truffaut** [comment]
What would be the laws and how would it compose with the rest of the optics?
Could you also give a few examples of `Intersection`?

**Comment by japgolly** [comment]
I played around with this some more. Interestingly, if we make it polymorphic it's uncomposable in the sense that
```
PIntersection[S, T, A, B] . PIntersection[A, B, C, D] ≠ PIntersection[S, T, C, D]
```

Upon discovering this, I'm not sure it's a great fit for inclusion into Monocle. The monomorphic version still has significant value though.

> What would be the laws

The same as `Iso[Option[A], Option[B]]` with an additional law that `None` always map to `None`. When that property holds, they are isomorphic.

> how would it compose with the rest of the optics?

Via `Iso[Option[A], Option[B]]` it can be turned into any other optic. On it's own it can also produce `Prism[Option[A], B]` and `Prism[Option[B], A]`. I haven't discovered anything else interesting yet.

> Could you also give a few examples of Intersection?

Sure, this kind of scenario:

```scala
sealed trait BobsFruit
object BobsFruit {
  case object Apple  extends BobsFruit
  case object Banana extends BobsFruit
}

sealed trait SolsFruit
object SolsFruit {
  case object Banana extends SolsFruit
  case object Orange extends SolsFruit
}

val BobAndSol = Intersection[BobsFruit, SolsFruit] {
  case BobsFruit.Apple  => None
  case BobsFruit.Banana => Some(SolsFruit.Banana)
} {
  case SolsFruit.Banana => Some(BobsFruit.Banana)
  case SolsFruit.Orange => None
}
```

And extending that, something like this where a common editor for fruit can be shared between specific types of fruit, say client fruits. Types of client fruits might not have a supported editor, and not all supported editors are used by client fruits. `FruitEditor.map` expresses that.
```scala
trait FruitEditor[Fruit, Editor] {
  def map[F](i: Intersection[Fruit, F]): FruitEditor[F, Editor] = ???
  def editor(f: Fruit): Option[Editor] = ???
}

sealed trait AllSupportedFruitEditors
object AllSupportedFruitEditors {
  case object Apple  extends AllSupportedFruitEditors
  case object Banana extends AllSupportedFruitEditors
  case object Mango  extends AllSupportedFruitEditors
}

type MainFruitEditor = FruitEditor[AllSupportedFruitEditors, WhatEver]
```

**Comment by puffnfresh** [comment]
@japgolly that sounds like an `Iso` lifted using `mapping`:

```haskell
mapping
  :: (Functor f, Functor g, Functor f1, Profunctor p) =>
     AnIso s t a b -> p (f a) (f1 (g b)) -> p (f s) (f1 (g t))
```

That is:

```haskell
intersection :: Iso' a b -> Iso' (Maybe a) (Maybe b)
intersection = mapping
```

It seems like your `FruitEditor` is just a `Profunctor`, specifically it's `Kleisli[Option, ?, ?]`.

**Comment by japgolly** [comment]
Awesome @puffnfresh! It's been ages since I looked at profunctors, can't remember much right now either. I'll have a good read on the weekend.

**Comment by japgolly** [comment]
@puffnfresh I don't think `mapping` would work in this case. `Iso' a b` is total in that all `a` correspond to `b` and vice-versa. What I have is like a partial iso in that some `a` correspond to `b` and vice-versa. To borrow from the slides for Julien's talk, my `Intersection` quasi-proposal is like [this](http://image.slidesharecdn.com/beyondscalalens-150312020754-conversion-gate01/95/beyond-scala-lens-23-638.jpg?cb=1442764862) except the circle on the right has a `?` area at the bottom too like the one on the left. It feels like a natural missing piece for which `Prism` is a specialisation.

> It seems like your `FruitEditor` is just a `Profunctor`, specifically it's `Kleisli[Option, ?, ?]`.

It looks like it because of the nature of `Intersection` but I don't think it is. Let me change the types to demonstrate. If it were a `Kleisli[Option, FruitA, Editor]` and I wanted to change the fruit to `FruitB`, then the Profunctoral `lmap` would expect `FruitB => FruitA` right? But such a (total) function is impossible, what we have is a `Option[FruitB] => Option[FruitA]`. I guess it would work as a `Kleisli[Option, Option[?], ?]` though.

**Comment by julien-truffaut** [comment]
Hi @japgolly, I don't think `Intersection[S, A]` can be seen as an `Iso[Option[S], Option[A]]` because it would not satisfy the law:

```
let i: Interestion[S, A]
forall s: S such as i.get(Some(s)) == None then i.reverseGet(i.get(Some(s))) != Some(s) 
since i.reverseGet(None) == None by definition
```

For a similar reason, `Intersection[S, A]` is not equivalent to `Prism[Option[S], A]`

**Comment by japgolly** [comment]
@julien-truffaut Inspired by some success I had used Haskell yesterday, I decided to play around with this in Haskell too. I believe the reverseGet/get law can satisfied using `Either` instead of `Option` under the hood (although I haven't prop tested). Code is here: https://gist.github.com/japgolly/aeb1e5e2f5689b913525

So I think the laws would be ok. The problem is composition. If the type is `Intersection s a` (or `Intr` for short), then `Intr a b * Intr b c = Intr a c` - no problem. But if we expand to `Intr s t a b` then I would expect that `Intr a b c d * Intr c d e f = Intr a b e f` but no such luck. It seems to result in `Intr a (b \/ d) e (d \/ f)`. Which is sad but seems to make sense.

And so at this point, it seems that all `Prism`s can be encoded as intersections, but not all `PPrism`s. 

Come to think of it, would `PPrism` having `A => B \/ S` have the same composition problem as I hit? I'll have to think about it next time and have a look. (Now I need a break after a long week.)

**Comment by julien-truffaut** [comment]
Hi @japgolly, apologize for the delay. I agree with you the `get - reverseGet` law seems to hold for `Intersection` but in fact I wonder what is the difference between `Iso[A \/ S, S \/ A]` and `Inter[S, A]` ? Is it just syntaxic sugar?

**Comment by julien-truffaut** [comment]
@japgolly do you think there is more to do in this topic or we can close it?

**Comment by japgolly** [comment]
Hi @julien-truffaut, sorry for the lack of activity. I'm still interested in this but busy with other things. Let's close this, I don't want to pollute Monocle's open issues. If I later discover anything interesting I'll let you know.

**Comment by julien-truffaut** [comment]
np feel free to reopen when you come back to it
