### ISSUE TITLE
Document missing non-backward compatible change

### ISSUE THREAD

**Issue by jedesah** [julien-truffaut/Monocle#351]
When upgrading, one needs to change `import monocle.syntax._` to `import monocle.syntax.all._`.

It would be nice if this were documented for others that want to make the upgrade.

**Comment by julien-truffaut** [comment]
Sorry we forgot to include in the release notes, it happened on this PR https://github.com/julien-truffaut/Monocle/pull/243 and as far as I can see it was between 1.2.0-M1 and 1.2.0-M2.

**Comment by NightRa** [comment]
@julien-truffaut Does it mean MIMA didn't catch it?

**Comment by julien-truffaut** [comment]
no it was intended to be a non backward compatible change between 1.1.0 and 1.2.0 but we missed it when we wrote the release notes. I used mima to check that 1.2.1 is backward compatible with 1.2.0 but this change was introduced in 1.2.0 (1.2.0-M2 to be exact)

**Comment by NightRa** [comment]
:+1:

**Comment by jedesah** [comment]
👍 Awesome!
