### ISSUE TITLE
Latest shapshot no longer binary compatible with scalaz 7.2.x

### ISSUE THREAD

**Issue by newhoggy** [julien-truffaut/Monocle#364]
Also, there have been no releases compatible with scalaz 7.2.x either.

**Comment by julien-truffaut** [comment]
monocle 1.2.x are released for scalaz 7.2.x:
- 1.2.1: https://github.com/julien-truffaut/Monocle/blob/v1.2.1/build.sbt#L37
- 1.2.0: https://github.com/julien-truffaut/Monocle/blob/v1.2.0/build.sbt#L33

I upgraded monocle snapshot to scalaz 7.3.0-M3 in prevision of monocle 1.3.x built against scalaz 7.3.x

Can you tell me more about your issue?

**Comment by newhoggy** [comment]
You're correct.

I was using some other library that had the `SNAPSHOT` as a transitive dependency.  After specifying`excludeAll` in `sbt` and then explicitly including monocle as a direct dependency, I was able to resolve the issue.

Thanks!
