### ISSUE TITLE
Add documentation on Optional to the website

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#370]

**Comment by mdulac** [comment]
I was looking for this documentation when I started to use Monocle.
I'll try to do it :)

**Comment by mdulac** [comment]
Is this example great for the documentation, according to you ?
https://gist.github.com/mdulac/bc453328a5a8980fd4288558c3e06e35

**Comment by mdulac** [comment]
Finally, I'm going to use your examples from your talk at Scala World : head and index functions, on list
