### ISSUE TITLE
Monocle sticker

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#375]
If by any chance we have an artist around, it would be awesome to make a monocle sticker e.g.

https://twitter.com/typelevel/status/741299243500097536?lang=en-gb

**Comment by aoiroaoino** [comment]
You mean, renew the logo?

**Comment by julien-truffaut** [comment]
We can renew the logo or we could have a simplified version that fit into an hexagone.

**Comment by julien-truffaut** [comment]
@DavidMorganBrow (twitter handle) proposed the following logo, I think it is really awesome:
![pasted image at 2016_11_11 11_32 am](https://cloud.githubusercontent.com/assets/1859417/20219149/ec8d121e-a81f-11e6-93cb-b3fa6e8ba822.png)

**Comment by aoiroaoino** [comment]
It's so cooool! I realy like it.
