### ISSUE TITLE
implicit lookup for lenses

### ISSUE THREAD

**Issue by drdozer** [julien-truffaut/Monocle#385]
I understand why lenses can't be typeclasses. However, there is a natural uniqueness constraint between a type, each field and the field type. With shapeless, instances can be lifted as singleton types. So the name of the field could be lifted as a singleton.

The type pair `[MyCaseClass, 'fieldName]` is unique so can be used for a typeclass.

```
trait FieldOptic [A, F] {
  type B

  def asLens: Lens[A, B]
}
```

or

```
implicit def fieldIndex[A, F, B](implicit ev: FieldOptic.Aux[A, F, B]): Index[A, F, B] = ...
```

**Comment by julien-truffaut** [comment]
`Index` would give you an `Optional` but `At` supply a `Lens`
