### ISSUE TITLE
Keep reference equality if possible

### ISSUE THREAD

**Issue by scalasolist** [julien-truffaut/Monocle#388]
It is a feature request.

I need to check if updating a value with lens made any difference. For example

    final case class Person(name : String, age : Int)
    val ageL = Lens[Person, Int](_.age)(a => _.copy(age = a))
    val before = Person("John", 12)
    val after = ageL.set(12)(before)

In that case `before eq after` returns `false`, but `before equals after` returns `true`. Running full check with `equals` has high cost, especially if structure has many layers of nested substructures. And comparing reference equality costs nothing. 

I may add wrap to a setter:

    val ageW = Lens[Person, Int](_.age)(a => p => if (p.age == a) p else p.copy(age = a))

But that would not solve the entire problem, if I have long nested structure, the change would be propagated from the bottom to the up, making the same wrapper checks on each step. I need some method to abort entire calculation if the bottom is proofed to have no changes and return immediately. And I believe I could not solve the issue on user level, it could be only solved on the library level, if it would provide some way to abort composite setters prematurely.

**Comment by julien-truffaut** [comment]
it should be possible to pimp `Lens` to get your behaviour:

```scala
implicit class LensEq[S, A](lens: Lens[S, A]){
  def modifyEq(f: A => A): S => S = s => {
    val a = lens.get(s)
    val a2 = f(a)
    if(a eq a2) s else lens.set(a2)(s)
  }
  def setEq(a: A): S => S = modifyEq(_ => a)
}
```
