### ISSUE TITLE
monocle-law holding us back

### ISSUE THREAD

**Issue by paulp** [julien-truffaut/Monocle#399]
The most recently published version of monocle-law (1.2.2) is built against discipline 0.4, which in turn is built against specs2-core 3.6 and scalacheck 1.12.4, both of which are binary incompatible with everything recent.

discipline 0.5 (the version seen at the repository head) jumps to 3.7.3/1.13.1, but an even better target would be the current discipline 0.7, which is specs2 3.8.5 and scalacheck 1.13.2.

New artifacts would be greatly appreciated - thanks.

**Comment by paulp** [comment]
Oh, I should also mention that specs2 3.8.5 is built against scalaz 7.2.6, but the monocle repository currently has scalaz at 7.3.0-M3. So if you do build new artifacts it would be great if the scalaz version were consistent with the dependencies.

**Comment by julien-truffaut** [comment]
Sure, I started to prepare a PR to release 1.3.0 with the requested dependency upgrade. I was hoping to wait for scalaz 7.3 before breaking binary compatibility but we can very well release 1.4.0 once scalaz is available.

Could you please check the PR to see if you're happy with the dependencies?

**Comment by julien-truffaut** [comment]
@paulp 1.3.0 is on its way to maven central, please tell me if you encounter any issue

**Comment by paulp** [comment]
@julien-truffaut Thanks a lot. Unfortunately as an ecosystem we seem to really enjoy busywork. It turns out scalaz-scalacheck-binding 7.2.6 is built against scalacheck 1.12.5. This takes the number of workable version combinations for the matryoshka dependencies down to zero. We will have to break some dependencies to make progress.

**Comment by julien-truffaut** [comment]
Arf I should have released an RC to check that.

Yesterday when I tried to upgrade argonaut to monocle 1.3.0, it seems that the scalaz tests passed (but not the cats ones), maybe you could exclude scalacheck from scalaz-scalacheck-binding, see:
https://github.com/argonaut-io/argonaut/pull/249
https://github.com/argonaut-io/argonaut/blob/57851043c86869c7ae11ed498f6dbc7b2015f405/project/build.scala#L21

Otherwise, it is worth to ask scalaz to release a scalaz-scalacheck-binding for scalacheck 1.13.x

**Comment by paulp** [comment]
@julien-truffaut See my comment there - I find it improbable this problem can be overcome with exclusions. The die is cast by how the dependencies were built.

**Comment by julien-truffaut** [comment]
it makes sense, so I guess we have to wait for scalaz 7.3 or I can release a monocle 1.4.0-M1 against scalaz 7.3.0-M5 ...

**Comment by julien-truffaut** [comment]
@paulp @xuwei-k cross released scalaz 7.2.7 with scalacheck 1.12 and 1.13. This should fix your issues in matryoshka

**Comment by paulp** [comment]
@julien-truffaut Thanks a lot.
