### ISSUE TITLE
Generalised Lenses to support class with type parameter

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#4]
example: case class Id[T](value: T)

val intId = Id(1)

IdLens.set(intId, "1") ==> Id[String]("1")
IdLens.modify(intId, _ + 2L) ==> Id[Long](3)

**Comment by Krever** [comment]
@julien-truffaut Is there example somewhere?

**Comment by julien-truffaut** [comment]
@Krever here is an example of polymorphic `Prism` or `PPrism`: https://github.com/julien-truffaut/Monocle/blob/master/core/shared/src/main/scala/monocle/std/Option.scala#L10
