### ISSUE TITLE
Release for Scala v2.12.0

### ISSUE THREAD

**Issue by aoiroaoino** [julien-truffaut/Monocle#407]
we needs:
- [x] refined https://github.com/fthomas/refined/issues/214
- [x] shapeless https://github.com/milessabin/shapeless/issues/651
- [x] macro-compat 
- [x] macro-paradise https://github.com/scalamacros/paradise/issues/87
- [x] discipline https://github.com/typelevel/discipline/issues/28
- [x] scalacheck https://github.com/rickynils/scalacheck/issues/291

**Comment by xeno-by** [comment]
https://oss.sonatype.org/content/repositories/releases/org/scalamacros/paradise_2.12.0/

**Comment by aoiroaoino** [comment]
thanks! @xeno-by

**Comment by fthomas** [comment]
refined is now available for 2.12: https://oss.sonatype.org/content/repositories/releases/eu/timepit/refined_2.12/

**Comment by aoiroaoino** [comment]
thanks! @fthomas

**Comment by julien-truffaut** [comment]
@fthomas is refined 0.6 binary compatible with 0.5?

**Comment by larsrh** [comment]
@julien-truffaut discipline `0.7.2` is out now.

**Comment by julien-truffaut** [comment]
@larsrh cheers

**Comment by fthomas** [comment]
@julien-truffaut Yes, refined 0.6.0 is binary compatible with 0.5.0. The version bump is due to upgrading refined-scalacheck from ScalaCheck 1.12 to 1.13.

**Comment by julien-truffaut** [comment]
cheers
