### ISSUE TITLE
Distinguish experimental modules

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#440]
We should make it explicit which module is experimental (i.e. where we might break binary compatibility)

**Comment by kubum** [comment]
Summary of discussion

**core** - binary compatable
**macro** - binary compatable
**laws** - binary compatable
**generic** - experimental
**refined** - experimental
**unsafe** - experimental
**tests** - ignore
**bench** - ignore
**docs** - ignore

**Comment by julien-truffaut** [comment]
**state ** is also missing from the list, it should be experimental
