### ISSUE TITLE
add greater Prism

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#449]
`def greater[T](n: T)(implicit nt: Numeric[T]): Prism[T, T Refined Greater[n.type]]`

**Comment by fthomas** [comment]
@julien-truffaut I was experimenting with creating Prisms generically from any refined type here https://github.com/fthomas/refined/issues/169. Do you think something like that could provide the functionality of `greater`? (Btw, `Greater[N]`  needs a type param and I don't see which one it should have based on the signature of `greater`.)

**Comment by julien-truffaut** [comment]
@fthomas Yes I think it makes sense. I also thought there should be a way to automatise this but I wanted to go through a few manual `Prism` definition in order to see the pattern.

You're correct about `greater`, I updated the signature.

**Comment by fthomas** [comment]
That sounds like a good plan.

But the return type of `greater` still looks odd to me. It should be something like `Prism[T, T Refined Greater[X]]` where `X` is a lower bound on the refined `T`, right? But what should `X` be in this case? If you want to use `n.type`, the type parameter `T` needs to be a subtype of `AnyRef` (see the [Scala Language Specification, section 3.2.1](http://www.scala-lang.org/files/archive/spec/2.11/03-types.html#singleton-types)) which would disallow `AnyVal`s like `Int` or `Double`. This restriction is only lifted in the SIP-23 PR with `-Yliteral-types`. In current Scala this limitation can only be circumvented by using [`shapeless.Witness`](https://github.com/fthomas/refined/blob/master/docs/dependent_refinement.md#shapeless-to-the-rescue).

**Comment by julien-truffaut** [comment]
Ah you're completely right, I didn't encode the lower bound `n` in the type. Ok so maybe we should delay this task until `SIP-23` or use `Witness` in the meantime.

**Comment by fthomas** [comment]
Since the goal is to have another specific `Prism` definition to see how those implementations could be unified, we could add for example:
```
def startsWith(prefix: String): Prism[String, String Refined StartsWith[prefix.type]]
```
This is in spirit similar to `greater` but avoids all the problems of an `AnyVal` singleton type.

**Comment by julien-truffaut** [comment]
good idea, let's open a new issue for `startsWith`

**Comment by julien-truffaut** [comment]
We can reopen this issue after `SIP-23`
