### ISSUE TITLE
[Question] Updating all fields of a type in a case class

### ISSUE THREAD

**Issue by Daenyth** [julien-truffaut/Monocle#459]
Suppose I have
```scala
case class Foo(a: Int, b: Bar)
case class Bar(c: Int, d: String, e: Int)
```
How can I make an optic that will mutate all the ints?

```scala
val optic: ?[Foo, Int] = ???
optic.modify(_+1)(Foo(1, Bar(2, "a", 3))) == Foo(2, Bar(3, "a", 4))
```

**Comment by julien-truffaut** [comment]
At the moment, we do not have a way to do it but it might be possible to implement it in `monocle-generic` using shapeless.

Currently, you should be able to do (sorry I don't have a compiler available, so there might be a typo):
```scala
case class Point(x: Int, y: Int)

import monocle.function.all._ // to get each
import monocle.generic.product._ // to get each instance for Product
import monocle.syntax.apply._ // to use applyTraversal

Point(2, 3).applyTraversal(each).modify(_ + 1) // Point(3, 4)
```

So it is limited to case classes that contains only values of one type.

**Comment by julien-truffaut** [comment]
Also if you are ready to specify all fields manually, you could do:

```scala
val foo = GenLens[Foo]
val ints = Traversal.applyN(foo.a, foo.b.c, foo.b.e)

ints.modify(_ + 1)(Foo(1, Bar(2, "a", 3)))
```

**Comment by Daenyth** [comment]
The `applyN` looks promising; what if my `b` is actually an `Option[Bar]`? Would I do `Traversal.applyN(foo.a, foo.b.map(_.c), foo.b.map(_.e))`?

**Comment by julien-truffaut** [comment]
Currently, `applyN` only takes `Lens`, so if you have an `Option` in your path you will need to use `Optional`. We could create an `applyN` taking `Optional` or try to make `applyN` use a mix of `Lens` and `Optional` but I am not sure how to do that with varargs.

If we had an `applyN` for `Optional` you could do:

````scala
import monocle.std.option.some

val maybeB = GenLens[Foo](_.b) composePrism some
Traversal.applyN(GenLens[Foo](_.a).asOptional, maybeB composeLens GenLens[Bar](_.c), maybeB composeLens GenLens[Bar](_.e))
```

So it becomes more verbose :/

**Comment by Daenyth** [comment]
Verbose yes, but it seems boilerplate-y in a way that shapeless could in theory automatically derive. Then again I'm no shapeless expert, so I can't say for certain

**Comment by julien-truffaut** [comment]
can we close this @Daenyth ?
