### ISSUE TITLE
Support java 7 with scala 2.11

### ISSUE THREAD

**Issue by gwils** [julien-truffaut/Monocle#462]
I have had a compilation error trying to use Monocle 1.3.2 in a Java 7 environment. Please build monocle for Java <8 with Scala 2.11 if you can do so without sacrificing functionality.

Yes, Oracle Java 7 is EOL, I know, but I am working on several projects which target the IBM JVM, where 7 is still very much the norm.

**Comment by julien-truffaut** [comment]
I don't remember why did I change the config: https://github.com/julien-truffaut/Monocle/commit/230a9a3d27b3c829cd94b90548207a112f756fa0

Maybe it was just a try that wasn't supposed to be released or we used it when we experimented with java8 date.

Anyway, we should aim to quickly release 1.4.0-M2 supporting java 7 for scala 2.11

**Comment by julien-truffaut** [comment]
I will soon release 1.4.0-M2 with this fix

**Comment by julien-truffaut** [comment]
@gwils 1.4.0-M2 is released, can you please give it a try?
