### ISSUE TITLE
Add uuid Prism

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#485]
```
val uuid: Prism[String, UUID]
```

We can add it in core.std.string as I don't think we need `refined`

**Comment by mjjc** [comment]
Hello. I actually coded this feature, but then realised I shouldn't use `java.util.UUID` in `shared`. What UUID class should we use there?

**Comment by julien-truffaut** [comment]
Is it because there is no `UUID` in scala.js?

**Comment by mjjc** [comment]
That's exactly what I thought 5 minutes ago, but now I realised scala.js implements part of java API.

https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/UUID.scala
