### ISSUE TITLE
regression: can't build source jar (java.util.zip.ZipException: duplicate entry: monocle/std/String.scala)

### ISSUE THREAD

**Issue by SethTisue** [julien-truffaut/Monocle#492]
`java.util.zip.ZipException: duplicate entry: monocle/std/String.scala `

spotted in the Scala community build at e.g https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/152/consoleFull

reproducible locally with:

    ++2.12.1
    coreJVM/packageSrc

if this hasn't shown up in your own CI, probably it's because your CI runs don't package up source JARs

I believe the responsible commit is f7177b589b59171a2a72e27202f195bd50ee73f0

cc @mjjc

**Comment by julien-truffaut** [comment]
Thank you very much @SethTisue for the bug report and for your investigation. 

@n4to4 @xuwei-k do you have an idea how to fix it?

```
monocle] [error] (coreJVM/compile:packageSrc) java.util.zip.ZipException: duplicate entry: monocle/std/String.scala
```

**Comment by n4to4** [comment]
@julien-truffaut
Looks like `core/jvm/src/main/scala/monocle/std/String.scala` should have been renamed to something like `core/jvm/src/main/scala/monocle/std/PlatformSpecificString.scala`

**Comment by SethTisue** [comment]
LGTM, thanks!
