### ISSUE TITLE
Modify 1 to N relation

### ISSUE THREAD

**Issue by jCalamari** [julien-truffaut/Monocle#503]
Hi,

sorry for raising this as an issue, however Monocle google group seems empty.

Can you share example how to filter/modify 1 to many relation, please?

Given a case class:

```
case class Address(streetName: String)
```

And 1 to many relation:

```
case class User(addresses: List[Address])
```

How to modify `addresses` that match some criteria?

Many thanks!

**Comment by julien-truffaut** [comment]
Np @jCalamari, don't hesitate to create an issue or ask on gitter if you have any questions.

To answer your question, you can filter a `List` using `each` and `unsafeSelect` (from `insafe` module):

```
import monocle.function.all._ // for each
import monocle.syntax.all._   // for applyTraversal which gives us a better type inference
import monocle.unsafe.UnsafeSelect.unsafeSelect

val users: List[User] = ???
users.applyTraversal(each).composePrism(unsafeSelect(_.length > 3)).getAll 
// get all users adresses which have more than 3 characters
```

Please read the following doc to understand why it is considered unsafe: http://julien-truffaut.github.io/Monocle/unsafe_module.html

**Comment by julien-truffaut** [comment]
@jCalamari if it answers your question, can you close the issue. Otherwise feel free to ask for more details
