### ISSUE TITLE
Consider putting Shrink constraints on laws

### ISSUE THREAD

**Issue by travisbrown** [julien-truffaut/Monocle#527]
Right now methods like `PrismTests.apply` take `Arbitrary` instances but not `Shrink`, which means that the default (no-op) `Shrink` instances will be used during laws checking.

This is kind of annoying in circe—every time I break something in circe-optics I get hundreds of lines of error output because my arbitrary `Json` values can be quite large. I have nice `Shrink` instances for all of my types, but they're not getting used because they can't get past the `Shrink`-constraint-less generic laws methods.

What do you think? Adding these constraints would be mostly source compatible, since the default `Shrink` instances would still get plugged in, just a little higher up (it would break code that passes in the implicit arguments explicitly, though).

**Comment by travisbrown** [comment]
(I should clarify that I'm happy to do the work, but wanted to check before putting together a PR.)

**Comment by julien-truffaut** [comment]
sounds good to me. Thanks for proposing to work on the PR :)

**Comment by julien-truffaut** [comment]
It seems you implemented it in circe. Feel free to PR back.
