### ISSUE TITLE
Please ascribe types for generated lenses

### ISSUE THREAD

**Issue by tpolecat** [julien-truffaut/Monocle#530]
The `@Lenses` annotation doesn't annotate the types for the members it generates, which sets off WartRemover's `org.wartremover.warts.PublicInference` wart. So it would be nice to add this if it's not too much trouble. Thanks!

**Comment by tpolecat** [comment]
I will try to fix this one.

**Comment by tpolecat** [comment]
Well, adding the type annotations doesn't stop the warning for some reason.

**Comment by julien-truffaut** [comment]
Interesting, maybe it is worth cross posting in wart remover?

**Comment by julien-truffaut** [comment]
@tpolecat do you think we can close this?

**Comment by tpolecat** [comment]
I will work on it some more today and either open a PR or close it. Thanks for the reminder.

**Comment by julien-truffaut** [comment]
np, there is nothing urgent. Just doing a bit of housekeeping for once ^^

**Comment by tpolecat** [comment]
More detail for reference. So, after adding type annotations the following still gets the WartRemover warning:

```scala
@Lenses case class Foo(n: Int, s: String)
```

But the tree it generates compiles fine:

```scala
case class Foo(n: Int, s: String);
object Foo {
  val n: monocle.Lens[Foo, Int] = monocle.macros.internal.Macro.mkLens[Foo, Foo, Int, Int]("n");
  val s: monocle.Lens[Foo, String] = monocle.macros.internal.Macro.mkLens[Foo, Foo, String, String]("s")
}
```

I'm going to see if I can track it down in WartRemover.

**Comment by tpolecat** [comment]
The wart malfunctions on the macro-generated tree but works correctly if I copy/paste the generated code into the test. So there is a difference in the tree attributes. We may be able to flag the generated code as synthetic and bypass wartremover altogether. I asked the propellerheads in scala/contributors.

**Comment by julien-truffaut** [comment]
@tpolecat do you care about that one or can I close it?

**Comment by tpolecat** [comment]
Feel free to close, I'm not using WartRemover anymore.
