### ISSUE TITLE
Lens.zip

### ISSUE THREAD

**Issue by pandemonium** [julien-truffaut/Monocle#545]
Dear Monoclers,

I found myself wanting to zip Lenses so that I can update multiple fields "at once." 

```
def zip[S, A, B](l: Lens[S, A], r: Lens[S, B]): Lens[S, (A, B)] =
    Lens((s: S) => (l.get(s), r.get(s)))((ab: (A, B)) => (s: S) => r.set(ab._2)(l.set(ab._1)(s)))
```

So, as part of playing around with a 6502-interpreter, I can encode the ADC-instruction as a lens spanning the A and Flags fields of a case class:

```
@Lenses
case class CpuState(a: Int, x: Int, y: Int, sp: Int, pc: Int, flags: Int)

```
So that I can:
```
def adc(a: Int, flags: Int): (Int, Int) = ???

zip(CpuState.a, CpuState.flags) modify { case (a, flags) => adc(a, flags) }
```

Now, looking around and reading whatever I could find about Monocle, I cannot seem to understand if "this" is already in Monocle and/ or if there's another Correct way of doing this.

Thank you!

**Comment by julien-truffaut** [comment]
Hi @pandemonium, unfortunately `zip` is unlawful for lenses. It breaks the composition law when two lenses overlap: https://github.com/julien-truffaut/Monocle/blob/master/core/shared/src/main/scala/monocle/law/LensLaws.scala#L24-L25

**Comment by pandemonium** [comment]
Ahh - I saw that and thought that could be the reason. This is not a problem for me in this case though so I’ll just keep the zip. Thank you for taking the time to answer!
