### ISSUE TITLE
Getting path from lens as a string

### ISSUE THREAD

**Issue by stijndehaes** [julien-truffaut/Monocle#549]
Hi,

I am very interested in your library to use it our validation framework. I would use lenses to specify the paths of the variable that need to be validated. But when a validation returns an error I need to give them a string representing the path. For example:

case class User(name: String, address: Address)
case class Address(street: String)

When I am validating street I pass a lens for the user object that get's the street field. If validation return an error I need the path: address.street to return as information to the FE.

I can't seem to find any method that returns the path from a lens however. Do you know if this is possible?

Kind Regards,
Stijn De Haes

**Comment by julien-truffaut** [comment]
Hi,

Sorry, optics do know the path. In fact, optics can point toward things that are not fields of case classes.
