### ISSUE TITLE
Could we add a ArrayIndex ?

### ISSUE THREAD

**Issue by russellyou** [julien-truffaut/Monocle#563]
I can see there are build in 

listIndex
streamIndex
vectorIndex

But I have some case class using Array to with better with Java.  

I have added my own one which works fine.

    implicit def arrayIndex[A]: Index[Array[A], Int, A] = new Index[Array[A], Int, A] {
      def index(i: Int) = Optional[Array[A], A](
      l      => if(i < 0) None else l.drop(i).headOption)(
(a:A) => (l:Array[A]) => if(i < 0) l
      else{
  val cloned = l.clone()
  cloned(i) =a
  cloned
})
    }

Let me know whether it's good idea. Thanks !

**Comment by julien-truffaut** [comment]
Hi @russellyou, monocle only supports immutable data structure.

**Comment by russellyou** [comment]
Understand that.  Thanks @julien-truffaut 

if we clone the Array before changing the element, could we treat it as effective immutable even the Array itself is mutable. 

Not sure whether my case is special, for working with Java, many of my case class contain Array. It will be good to have a consistent way(lens) to access the deep embedded fields. 

Thanks !

**Comment by julien-truffaut** [comment]
yes, if you clone it before changing the element it will be like an immutable array. It is completely fine that you use it this way but I don't think it is something that should be defined in monocle.

**Comment by russellyou** [comment]
OK. Close this issue then.
