### ISSUE TITLE
Scala 2.13.0-M4

### ISSUE THREAD

**Issue by xuwei-k** [julien-truffaut/Monocle#575]
- [x] https://github.com/fthomas/refined/pull/512
- [x] https://github.com/typelevel/discipline/pull/54
- [x] https://github.com/tpolecat/tut/pull/225

**Comment by julien-truffaut** [comment]
refined seems to be ready

**Comment by julien-truffaut** [comment]
I propose that we remove support for 2.10

**Comment by fthomas** [comment]
refined is not yet published for M4. I'll notify you when that happens.

**Comment by xuwei-k** [comment]
removed Scala 2.10 support https://github.com/julien-truffaut/Monocle/commit/b01a0cc97f09864a80a63076e3b260163ed59efd

**Comment by fthomas** [comment]
Sorry for the delay, I had trouble publishing refined 0.9.1 for M4. But as @xuwei-k already noted in #579, refined 0.9.2 is now available and published for M4.

**Comment by julien-truffaut** [comment]
@fthomas np there is no rush ;)

**Comment by tpolecat** [comment]
tut 0.6.6 is out for 2.13.0-M4, sorry for the delay
