### ISSUE TITLE
publish for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by SethTisue** [julien-truffaut/Monocle#596]

**Comment by xuwei-k** [comment]
https://github.com/julien-truffaut/Monocle/pull/605

**Comment by julien-truffaut** [comment]
Should I release 1.6.0-M1 for all currently supported scala version?

**Comment by SethTisue** [comment]
that's usually what users want, so they don't have to add "if Scala version this, Monocle version that" conditionals to their builds

**Comment by julien-truffaut** [comment]
I had to release manually as I got some issues with sbt sonatype. 1.6.0-M1 should be available soon.

**Comment by SethTisue** [comment]
scala/make-release-notes@75b22fc956980381df7b836986a7828e410b996b
