### ISSUE TITLE
Prepare release note for 1.6.0

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#614]
Diff all changes between master -> `1.5.0` tag and cats -> `v1.5.1-cats ` tag

**Comment by harmeetsingh0013** [comment]
Hi @julien-truffaut ,

I was trying to compare these two tags, but these are not available in git `/compare` drop down. Could you please help me, if I did something wrong.

**Comment by harmeetsingh0013** [comment]
Hey @julien-truffaut,

I figured out the changes between [master -> 1.5.0](https://github.com/julien-truffaut/Monocle/compare/v1.5.0...master) and [cats -> v1.5.1-cats](https://github.com/julien-truffaut/Monocle/compare/v1.5.0-cats...cats). So, the question is release notes for `1.6.0` version is the combination of these two differences or something else? 

This is the first time, I am doing these types of things, I apologize for huge question lists :stuck_out_tongue:
