### ISSUE TITLE
Investigate way to release from CI

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#616]
Ideally I would love to be able to create a tag and the pipeline will be in charged of publishing artifacts.

**Comment by pepegar** [comment]
Hi! I've used https://github.com/olafurpg/sbt-ci-release for publishing https://github.com/pepegar/hammock and it works like a charm.

I'd love to help with this but it requires adding secrets to travis & having sonatype permissions so I believe I can't help much here.  Feel free to answer here or get inspiration from the usage I'm doing in `hammock` of `sbt-ci-release` :)

**Comment by julien-truffaut** [comment]
thanks I will have a look @pepegar

**Comment by julien-truffaut** [comment]
@pepegar I followed all the instructions until updating `.travis.yml` but I am not sure how to adapt our current `travis.yml`.

**Comment by pepegar** [comment]
Hey @julien-truffaut 

If I understand your travis.yml correctly, the only place we'd need to change would be line 48, changing the `+publish` with `ci-release`?

```diff
modified   .travis.yml
@@ -45,7 +45,7 @@ install:
   - gem install sass
   - gem install jekyll -v 3.8.5
 after_success:
-- '[[ $TRAVIS_BRANCH == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]] && { sbt +publish ghpagesPushSite; };'
+- '[[ $TRAVIS_BRANCH == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]] && { sbt ci-release ghpagesPushSite; };'
 matrix:
   include:
   - scala: 2.11.11
```

**Comment by julien-truffaut** [comment]
Thanks @pepegar 

I tried that, the build was succesful but as far as I can see it didn't publish anything. I can't find any details of what happened in this after_succses phase: https://travis-ci.org/julien-truffaut/Monocle/jobs/513749686

**Comment by pepegar** [comment]
Hi again :)

The step is being evaluated, but the boolean condition we have is probably wrong and doesn't evaluate to true for tags. look at https://travis-ci.org/julien-truffaut/Monocle/jobs/513749686#L3396, it's being run.

What I'd do is going to travis and hitting debug build (IDK if that's available for opensource builds), and, once you're sshd into the box, `echo $TRAVIS_BRANCH`, because that's probably not `master` when pushing tags.

**Comment by julien-truffaut** [comment]
Ah thaks for the tip, I requested debug access to the build. I will investigate

**Comment by pepegar** [comment]
NP mate, report back if you need anything and I'll try to help

**Comment by julien-truffaut** [comment]
@pepegar You were right, I got:
```
echo $TRAVIS_BRANCH
v1.6.0-M3
```

**Comment by pepegar** [comment]
Hum, then I think you’ll need to change that condition in the Travis yaml

**Comment by julien-truffaut** [comment]
It worked! 1.6.0-M4 was released today for all versions.

Thank you very much @pepegar , @dwijnand  and @xuwei-k.
