### ISSUE TITLE
GenLens with two type parameters

### ISSUE THREAD

**Issue by maxkorolev** [julien-truffaut/Monocle#622]
I like making Products with non repeat types. For example:
```scala
case class A(value: Int) extends AnyVal
case class B(value: String) extends AnyVal
case class Pr(a: A, b: B)
```
So it would be very useful to make generating lens like that `GenLens[Pr, A]` for me. It's very simple to make with `shapeless.ops.hlist.Selector`. What would you say if I made pr? 
Btw, is this bad to make lenses, prisms, etc as implicit instances in such case?
```scala 
implicit val PrALens = GenLens[Pr](_.a)
implicitly[Lens[Pr, A]] // (Pr, A) is unique
```

**Comment by julien-truffaut** [comment]
Optics are not typeclasses, there are generally not unique for a given type. Even in your example, there are many `Lens[A, Int]` even in the case where you only have one `Int`, e.g.

```scala
val inc: Iso[int, Int] = Iso(_ + 1)(_ - 1)

val x: Lens[A, Int] = Genlen[A](_.value)
val y: Lens[A, Int] = Genlen[A](_.value) composeIso inc
```

**Comment by maxkorolev** [comment]
Well, I see. I would say that Isomorphism between Int and Int is identity, than right case of your example is:
```scala
val inc: Iso[int, Int] = Iso(identity)(identity)

val x: Lens[A, Int] = Genlen[A](_.value)
val y: Lens[A, Int] = Genlen[A](_.value) composeIso inc
```
Yeah, there are a lot of different cases, for example
```
Iso1 = A<->B<->C
Iso2 = A<->D<->C
Iso1 =?= Iso2
```
I know that optics are not typeclasses, but imho, it would be great if they were.
Conversation is out of scope, thank you for reply and library. Closing issue
