### ISSUE TITLE
Reduction of support

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#643]
This issue is mostly for maintainers: @NightRa, @aoiroaoino, @xuwei-k and @kenbot but feel free to comment if you are a Monocle user.

I am proposing to drastically reduce the support Monocle provides for various configurations to simplify the build, simplify the release process and make it easier for new contributors. Specifically, I would like to drop:
- scalaz 
- scala 2.11 (only support two major versions going forward)
- scala native

Monocle would still support Scala 2.12, 2.13 and scala.js.

I don't want to drop any of these configurations, but I reached a point where I can't make myself release a new version of Moncle because the release process annoys me so much and I don't have as much free time as I used to.

In my opinion, if some people/organisations want Monocle to support any additional platform/Scala version/library, they should either commit to supporting these features or offer some financial compensation such as we can either hire people to do it or take days off to do it ourselves.

Please let me know what you think about it.

**Comment by milessabin** [comment]
Would your position on scala-native change if they bumped to 2.12 or 2.13?

**Comment by julien-truffaut** [comment]
@milessabin not really, I don't want to complexify the build and the release process for something that I don't use and I don't know anyone who use/need it.

**Comment by puffnfresh** [comment]
My team heavily uses Scala 2.11, scalaz and Monocle. We're already stuck on old versions of lots of things so this would make Monocle be no different.

**Comment by julien-truffaut** [comment]
@puffnfresh Thanks for letting me know. I am sorry this would cause you and your team some pain.

**Comment by mdedetrich** [comment]
> @milessabin not really, I don't want to complexify the build and the release process for something that I don't use and I don't know anyone who use/need it.

Afaik, if scala native mirrored the releases of the official Scala compiler (just like Scala.js does) the extra build would be trivial (i.e. just a couple of extra lines). Its a shame that scala-native support is dropped, but I suppose at worst we can always fork.

**Comment by julien-truffaut** [comment]
Here is the PR I am working if we decide to move forward: https://github.com/julien-truffaut/Monocle/pull/646

Thanks @pepegar for the example build/travis.

If you are knowledgable about travis / sbt, I would appreciate a code review. I am just copy / pasting stuff hoping things will work out...

**Comment by julien-truffaut** [comment]
I am going forward and merge #646 

We can always discuss other options to support scalaz, scala native e.g. fork repo and advertise forks in Monocle web site
