### ISSUE TITLE
Fix compiler warning for 2.13

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#649]
After upgrading to 2.13 I noticed a bunch of warnings (deprecation?).

**Comment by spf3000** [comment]
Hey I started work on this.  PR should follow soon.  Will be my first OS contribution if successful!

**Comment by spf3000** [comment]
Might be slightly more involved than I thought - I think we are going to need to put in separate folders for scala 2.12 and scala 2.13 because some of the e.g. https://blog.ssanj.net/posts/2017-06-26-crosscompile-multiple-versions-of-scala-via-sbt.html
I thought I had better check with the maintainers as I don't think that there are any so far unless I am mistaken?

**Comment by julien-truffaut** [comment]
Thanks @spf3000 for looking into this issue. I just merged https://github.com/julien-truffaut/Monocle/pull/646 which makes scala 2.13 the "main" scala version for monocle. You might need to create a scala 2.12 folder to fix some warnings.

Maybe you can do it in two steps:
* fix all the warning you can without scala specific folder
* create a 2.12 specific folder for things like Stream who seem to have changed a lot.

**Comment by spf3000** [comment]
sounds like a plan :)

**Comment by julien-truffaut** [comment]
Hi @spf3000 , some of the warnings you may have been working on have been fixed in #651. Sorry about that it is rare that we get two people working on the same issue.

**Comment by spf3000** [comment]
No problems @julien-truffaut. Some of the compiler warnings are deprecation warnings for Stream, which is deprecated in favour of LazyList. I could change to LazyList, only problem is you are using scalaz-Tree in (Monocle/core/shared/src/main/scala/monocle/std/Tree) which is implemented in terms of Stream - so it might be a little difficult to move off Stream for the moment - some of the other warnings are easy to fix though - I can definitely reduce the number of warnings.

**Comment by julien-truffaut** [comment]
@spf3000 sounds good, let's tackle Stream separately

**Comment by spf3000** [comment]
Hey I have a commit ready - but I get permission denied - 
`ERROR: Permission to julien-truffaut/Monocle.git denied to spf3000.
fatal: Could not read from remote repository.`
Do i need to be added as  a contributor or something?

**Comment by julien-truffaut** [comment]
Hi @spf3000 ah yes that's because we use the fork - pull request model. I thought we had some links in the project but I can't find it anymore, you can have a look at https://gist.github.com/Chaser324/ce0505fbed06b947d962

Basically, you need to fork the project, do the changes on your fork and then open a pull request. 

Since you already made the change in this repo, you can fork it and then change your project remote

```
git remote set-url origin ${your project remote}
```

Does it make sense?

**Comment by spf3000** [comment]
https://github.com/julien-truffaut/Monocle/pull/655

**Comment by spf3000** [comment]
Ok - not sure if I did that right? ^^

**Comment by spf3000** [comment]
Hi @julien-truffaut  Please forget the last pull request - some git teething problems on my end - and review https://github.com/julien-truffaut/Monocle/pull/656

**Comment by julien-truffaut** [comment]
I believe we will have to live with the remaining warnings until we drop 2.12
