### ISSUE TITLE
Add Setter

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#765]
- [ ] Create `Setter`
- [ ] Create`AppliedSetter`
- [ ] `SetterSyntax`
- [ ] Make `Optional` inherit from `Setter` until we have `Traversal`

A `Setter` needs at least a `set`, `modify` and `compose` methods.  

Here is the current [version](https://github.com/julien-truffaut/Monocle/blob/master/core/shared/src/main/scala/monocle/Setter.scala). I propose that we implement the monomorphic version for now (i.e. 2 type parameters instead of 4).

**Comment by cquiroz** [comment]
I'll start working on this

**Comment by cquiroz** [comment]
Fixed by #779
