### ISSUE TITLE
Rename all compose methods to andThen

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#768]
Optics and functions compose in the same way; you need to make the type match a bit like in a puzzle.

```scala
def compose[A, B, C](f: B => C, g: A => B): A => C
def compose[A, B, C](f: Optic[A, B], g: Optic[B, C]): Optic[A, C]
```

You may have noticed that the parameters of optics composition are the inverse of function composition. Optics composition looks more like `andThen`  than `compose`.

```scala
def andThen[A, B, C](f: A => B, g: B => C): A => C
def compose[A, B, C](f: Optic[A, B], g: Optic[B, C]): Optic[A, C]
```

Therefore, I propose to rename all optics `compose` methods to `andThen`:

```scala
def andThenLens[A, B, C](f: Lens[A, B], g: Lens[B, C]): Lens[A, C]
def andThenPrism[A, B, C](f: Prism[A, B], g: Prism[B, C]): Prism[A, C]
// ...
```

For those curious about the abstraction behind function and optics, it is called [Category](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/arrow/Category.scala). 

We can also use the "standard" symbolic alias for `andThen`: `>>>` (see [Compose](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/arrow/Compose.scala)). 

```scala
person >>> address >>> streetNumber
```

**Comment by KacperFKorban** [comment]
I would like to work on this issue

**Comment by julien-truffaut** [comment]
All yours :)

**Comment by debian0501** [comment]
I’d like to do some beginner task. Is it possible to help here? Or is this task already in progress?

**Comment by julien-truffaut** [comment]
@debian0501 please go-ahead.

**Comment by aku258** [comment]
Hello, Is this issue still up for grabs. If yes, I'd like to work on it

**Comment by julien-truffaut** [comment]
@aku258 I believe @debian0501 started to work on it. I will try to add other beginner-friendly issues ASAP. Thanks for your interest.

**Comment by debian0501** [comment]
I'm sorry. I tried to make the task, but unfortunately I do not understand where I have to do the changes. Perhaps my knowledge of Scala is not good enough. Therefore, feel free to hand the task to another person @aku258 . Sorry !

**Comment by julien-truffaut** [comment]
It is probably because the description is not precise enough. 

In practice, it means renaming all methods that start with `compose` to `andThen` in the following repository https://github.com/julien-truffaut/Monocle/tree/3.x/core/shared/src/main/scala/monocle

For example, if a method is called `composePrism`, it becomes `andThenPrism`.

**Comment by debian0501** [comment]
Okay, that sounds easy. Thanks 🙏

**Comment by debian0501** [comment]
Okay, that sounds easy, so I will give it a try

**Comment by debian0501** [comment]
I only find two methods that start with compose: composeLens and composePrism in Optional.scala. Therefore I assume that the compose methods that do not have an addition should also be renamed. Example: Monocle/core/shared/src/main/scala/monocle/Iso.scala 

```scala
def compose[X](other: Iso[To, X]): Iso[From, X] = new Iso[From, X] {
    def get(from: From): X      = other.get(self.get(from))
    def reverseGet(to: X): From = self.reverseGet(other.reverseGet(to))
  }
```
is that correct?

**Comment by julien-truffaut** [comment]
Correct

**Comment by debian0501** [comment]
I stumbled upon three methods. Unfortunately, I can't find their definition:
composeTraversal
composeOptional
composeIso

Where are these methods defined? And can I get the rights to push my branch?

**Comment by julien-truffaut** [comment]
Yes the other methods hasn't been defined yet. We can do it in a separate PR.

We use the fork - pull request workflow such as you don't need to have right access to the main repo. Here are some documentation: https://gist.github.com/Chaser324/ce0505fbed06b947d962
