### ISSUE TITLE
Switch away from travis

### ISSUE THREAD

**Issue by cquiroz** [julien-truffaut/Monocle#769]
It seems travis is getting flaky. Should we switch to github actions?

**Comment by julien-truffaut** [comment]
Sounds good, do you know any pros and cons?

**Comment by cquiroz** [comment]
A nice pro is that any contributor will get actions to run without setting up travis
It seems to be more stable than travis too but only more experience will tell
`sbt-ci-release` works fine too
I don't see any cons really

**Comment by julien-truffaut** [comment]
Let's give it a try. In the worst case, we can always come back to travis.

**Comment by cquiroz** [comment]
Fixed by #772
