### ISSUE TITLE
Remove unused module

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#803]
In 3.x, we only have `core`, `dot-syntax`, `macro` modules. We should remove code for 2.x modules like `benchmark`, `doc`, `test`, `unsafe`, `state`.

**Comment by cquiroz** [comment]
Do you think we should remove law as well?

**Comment by julien-truffaut** [comment]
@cquiroz yes, you good point. Let's remove all dead code.
